/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CallLog } from "./CallLog";
import { CallLogCountArgs } from "./CallLogCountArgs";
import { CallLogFindManyArgs } from "./CallLogFindManyArgs";
import { CallLogFindUniqueArgs } from "./CallLogFindUniqueArgs";
import { DeleteCallLogArgs } from "./DeleteCallLogArgs";
import { CallLogService } from "../callLog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => CallLog)
export class CallLogResolverBase {
  constructor(
    protected readonly service: CallLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "CallLog",
    action: "read",
    possession: "any",
  })
  async _callLogsMeta(
    @graphql.Args() args: CallLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [CallLog])
  @nestAccessControl.UseRoles({
    resource: "CallLog",
    action: "read",
    possession: "any",
  })
  async callLogs(
    @graphql.Args() args: CallLogFindManyArgs
  ): Promise<CallLog[]> {
    return this.service.callLogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => CallLog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "CallLog",
    action: "read",
    possession: "own",
  })
  async callLog(
    @graphql.Args() args: CallLogFindUniqueArgs
  ): Promise<CallLog | null> {
    const result = await this.service.callLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CallLog)
  @nestAccessControl.UseRoles({
    resource: "CallLog",
    action: "delete",
    possession: "any",
  })
  async deleteCallLog(
    @graphql.Args() args: DeleteCallLogArgs
  ): Promise<CallLog | null> {
    try {
      return await this.service.deleteCallLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
